<?php

namespace Database\Seeders;

use App\Models\TransferStudent;
use Illuminate\Database\Seeder;

class TransferStudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transferStudents = [
            [
                'full_name' => 'Ahmad Rizki Pratama',
                'nisn' => '2345678901',
                'nis_previous' => 'SMA001234',
                'birth_place' => 'Jakarta',
                'birth_date' => '2007-03-15',
                'gender' => 'L',
                'religion' => 'Islam',
                'phone_number' => '081234567890',
                'email' => 'ahmad.rizki@email.com',
                'address' => 'Jl. Merdeka No. 123, Jakarta Pusat',
                'parent_name' => 'Budi Pratama',
                'parent_phone' => '081234567891',
                'parent_email' => 'budi.pratama@email.com',
                'parent_occupation' => 'Wiraswasta',
                'parent_address' => 'Jl. Merdeka No. 123, Jakarta Pusat',
                'previous_school_name' => 'SMA Negeri 1 Jakarta',
                'previous_school_address' => 'Jl. Sudirman No. 45, Jakarta',
                'previous_school_npsn' => '20104001',
                'previous_grade' => 'XI',
                'previous_major' => 'IPA',
                'previous_academic_year' => '2023/2024',
                'transfer_reason' => 'Pindah domisili karena pekerjaan orang tua',
                'desired_grade' => 'XI',
                'desired_major' => 'IPA',
                'raport_file' => 'transfer/raport/sample_raport_1.pdf',
                'photo_file' => 'transfer/photo/sample_photo_1.jpg',
                'family_card_file' => 'transfer/family_card/sample_kk_1.pdf',
                'transfer_certificate_file' => 'transfer/certificate/sample_cert_1.pdf',
                'birth_certificate_file' => 'transfer/birth_certificate/sample_birth_1.pdf',
                'original_grades' => [
                    'Matematika' => 85,
                    'Fisika' => 82,
                    'Kimia' => 88,
                    'Biologi' => 90,
                    'Bahasa Indonesia' => 87,
                    'Bahasa Inggris' => 85,
                ],
                'converted_grades' => [
                    'Matematika' => 85,
                    'Fisika' => 82,
                    'Kimia' => 88,
                    'Biologi' => 90,
                    'Bahasa Indonesia' => 87,
                    'Bahasa Inggris' => 85,
                ],
                'conversion_notes' => 'Nilai sudah sesuai dengan kurikulum sekolah',
                'status' => 'approved',
                'notes' => 'Siswa memenuhi syarat dan diterima',
                'submitted_at' => now()->subDays(10),
                'processed_at' => now()->subDays(2),
            ],
            [
                'full_name' => 'Siti Nurhaliza',
                'nisn' => '2345678902',
                'nis_previous' => 'SMA002345',
                'birth_place' => 'Bandung',
                'birth_date' => '2007-07-20',
                'gender' => 'P',
                'religion' => 'Islam',
                'phone_number' => '081234567892',
                'email' => 'siti.nurhaliza@email.com',
                'address' => 'Jl. Diponegoro No. 456, Bandung',
                'parent_name' => 'Hasan Nurdin',
                'parent_phone' => '081234567893',
                'parent_email' => 'hasan.nurdin@email.com',
                'parent_occupation' => 'PNS',
                'parent_address' => 'Jl. Diponegoro No. 456, Bandung',
                'previous_school_name' => 'SMA Negeri 2 Bandung',
                'previous_school_address' => 'Jl. Asia Afrika No. 78, Bandung',
                'previous_school_npsn' => '20219002',
                'previous_grade' => 'X',
                'previous_major' => 'IPS',
                'previous_academic_year' => '2024/2025',
                'transfer_reason' => 'Mengikuti orang tua yang mutasi kerja',
                'desired_grade' => 'XI',
                'desired_major' => 'IPS',
                'raport_file' => 'transfer/raport/sample_raport_2.pdf',
                'photo_file' => 'transfer/photo/sample_photo_2.jpg',
                'family_card_file' => 'transfer/family_card/sample_kk_2.pdf',
                'transfer_certificate_file' => 'transfer/certificate/sample_cert_2.pdf',
                'birth_certificate_file' => 'transfer/birth_certificate/sample_birth_2.pdf',
                'original_grades' => [
                    'Sejarah' => 88,
                    'Geografi' => 85,
                    'Ekonomi' => 90,
                    'Sosiologi' => 87,
                    'Bahasa Indonesia' => 89,
                    'Bahasa Inggris' => 83,
                ],
                'status' => 'pending',
                'notes' => null,
                'submitted_at' => now()->subDays(5),
            ],
            [
                'full_name' => 'Dedi Setiawan',
                'nisn' => '2345678903',
                'nis_previous' => 'SMA003456',
                'birth_place' => 'Surabaya',
                'birth_date' => '2006-11-10',
                'gender' => 'L',
                'religion' => 'Kristen',
                'phone_number' => '081234567894',
                'email' => 'dedi.setiawan@email.com',
                'address' => 'Jl. Pahlawan No. 789, Surabaya',
                'parent_name' => 'Robert Setiawan',
                'parent_phone' => '081234567895',
                'parent_email' => 'robert.setiawan@email.com',
                'parent_occupation' => 'Dokter',
                'parent_address' => 'Jl. Pahlawan No. 789, Surabaya',
                'previous_school_name' => 'SMA Kristen Petra Surabaya',
                'previous_school_address' => 'Jl. Ahmad Yani No. 12, Surabaya',
                'previous_school_npsn' => '20536003',
                'previous_grade' => 'XII',
                'previous_major' => 'IPA',
                'previous_academic_year' => '2023/2024',
                'transfer_reason' => 'Mencari lingkungan belajar yang lebih baik',
                'desired_grade' => 'XII',
                'desired_major' => 'IPA',
                'raport_file' => 'transfer/raport/sample_raport_3.pdf',
                'photo_file' => 'transfer/photo/sample_photo_3.jpg',
                'family_card_file' => 'transfer/family_card/sample_kk_3.pdf',
                'transfer_certificate_file' => 'transfer/certificate/sample_cert_3.pdf',
                'birth_certificate_file' => 'transfer/birth_certificate/sample_birth_3.pdf',
                'health_certificate_file' => 'transfer/health_certificate/sample_health_3.pdf',
                'original_grades' => [
                    'Matematika' => 92,
                    'Fisika' => 89,
                    'Kimia' => 91,
                    'Biologi' => 88,
                    'Bahasa Indonesia' => 85,
                    'Bahasa Inggris' => 90,
                ],
                'converted_grades' => [
                    'Matematika' => 90,
                    'Fisika' => 87,
                    'Kimia' => 89,
                    'Biologi' => 86,
                    'Bahasa Indonesia' => 85,
                    'Bahasa Inggris' => 88,
                ],
                'conversion_notes' => 'Nilai disesuaikan dengan standar kurikulum sekolah',
                'status' => 'pending',
                'notes' => 'Menunggu verifikasi dokumen',
                'submitted_at' => now()->subDays(3),
            ],
        ];

        foreach ($transferStudents as $data) {
            TransferStudent::create($data);
        }
    }
}
